In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
# ⭐️ accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

In [56]:
data = load_breast_cancer()

print(type(data))
print(dir(data))

<class 'sklearn.utils._bunch.Bunch'>
['DESCR', 'data', 'data_module', 'feature_names', 'filename', 'frame', 'target', 'target_names']


In [57]:
print(data.DESCR)

.. _breast_cancer_dataset:

Breast cancer Wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

:Number of Instances: 569

:Number of Attributes: 30 numeric, predictive attributes and the class

:Attribute Information:
    - radius (mean of distances from center to points on the perimeter)
    - texture (standard deviation of gray-scale values)
    - perimeter
    - area
    - smoothness (local variation in radius lengths)
    - compactness (perimeter^2 / area - 1.0)
    - concavity (severity of concave portions of the contour)
    - concave points (number of concave portions of the contour)
    - symmetry
    - fractal dimension ("coastline approximation" - 1)

    The mean, standard error, and "worst" or largest (mean of the three
    worst/largest values) of these features were computed for each image,
    resulting in 30 features.  For instance, field 0 is Mean Radius, field
    10 is Radius SE, field 20 is Worst Radius.

    - 

In [58]:
# 훈련에 사용될 data 가져옴 (실제 데이터는 대부분 대문자로 가져옴 !)
X = data.data 
# print(X)

# target값은 소문자로 사용
y = data.target
# print(y)

print(X.shape) # 실제 데이터는 569개, 암 환자 사용 feature은 30개 
print(len(y))

(569, 30)
569


In [59]:
# 데이터 분할(학습 80%, 테스트 20%) - 훈련할 데이터, 검증할 데이터로 나눠야 함
# 훈련할 때 검증 데이터도 같이하면 안됨. 꼭 나눠야 함 !!

# random_state: 데이터를 나눌 때 랜덤하게 섞는 과정을 "고정"시켜주는 값 (값은 아무값 줘도 됨)
#               "42"라는 시드(seed) 값을 고정해서, 몇 번을 실행하든 항상 똑같은 방식으로 섞이고 똑같이 나뉘게 만드는 것
#               어떤 숫자를 쓰든 상관없지만, 일단 정했으면 계속 같은 숫자를 써야 재현성이 생기는 것
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# X_oo의 행의 값과 y_oo의 결과값이 같아야 함
print(X_train.shape, y_train.shape) # (455, 30) (455,)
print(X_test.shape, y_test.shape)   # (114, 30) (114,)


(455, 30) (455,)
(114, 30) (114,)


# 1. LogisticRegression  분류 알고리즘

LogisticRegression( )알고리즘의 penalty='l2', *, dual=False, tol=0.0001, C=1.0, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver='lbfgs', max_iter=100, multi_class='deprecated', verbose=0, warm_start=False, n_jobs=None, l1_ratio=None  


1. ⭐️**penalty:**     
정규화 방법을 지정한다. 'l2'는 L2 정규화를 의미하며, 이는 가중치의 제곱합을 최소화하여 과적합을 방지하는 데 도움을 준다. 'l1'을 선택하면 L1 정규화를 사용하여 일부 가중치를 0으로 만들 수 있다. 'elasticnet'을 선택하면 L1과 L2 정규화를 혼합하여 사용할 수 있다.  

2. **dual:**  
이진 분류 문제에서 이중 문제를 해결할지를 결정한다. True로 설정하면 이중 문제를 해결하고, False로 설정하면 원래의 문제를 해결한다. 일반적으로 이진 분류에서는 False로 설정하는 것이 더 효율적이다.  

3. **tol:**  
수렴 기준을 설정합니다. 알고리즘이 수렴했다고 판단하는 기준으로, 기본값은 0.0001이다. 이 값이 작을수록 더 정밀한 수렴을 요구한다.  

4. ⭐️**C:**  
정규화 강도를 조절하는 하이퍼파라미터이다. 값이 작을수록 정규화가 강해지고, 값이 클수록 정규화가 약해진다. 기본값은 1.0이다.  

5. **fit_intercept:**  
절편(intercept)을 모델에 포함할지를 결정한다. True로 설정하면 절편을 포함하고, False로 설정하면 절편을 포함하지 않는다. 기본값은 True이다.  

6. **intercept_scaling:**  
다중 클래스 문제에서 절편을 조정하는 데 사용된다. 기본값은 1이며, 이 값은 절편의 스케일을 조정하는 데 사용된다.  

7. **class_weight:**  
클래스의 가중치를 설정한다. None으로 설정하면 모든 클래스의 가중치가 동일하게 설정됩니다. 클래스 불균형이 있는 경우, 특정 클래스에 더 높은 가중치를 부여하여 모델이 해당 클래스를 더 잘 학습하도록 할 수 있다.

8. **random_state:**  
난수 생성기의 시드를 설정합니다. 동일한 시드를 사용하면 동일한 결과를 재현할 수 있다. 기본값은 None이다.  

9. ⭐️**solver:**  
최적화 알고리즘을 선택한다. 'lbfgs', 'newton-cg', 'liblinear', 'sag', 'saga' 중 하나를 선택할 수 있다. 각 솔버는 서로 다른 특성과 성능을 가지므로 데이터셋에 따라 적절한 솔버를 선택하는 것이 중요하다.  

10. ⭐️**max_iter:**
알고리즘의 최대 반복 횟수를 설정한다. 기본값은 100이며, 이 값에 도달하기 전에 수렴하면 알고리즘이 종료된다.  

11. **multi_class:**  
다중 클래스 문제에서의 처리 방법을 설정한다. 'deprecated'는 더 이상 사용되지 않는 옵션이며, 대신 'ovr' (One-vs-Rest) 또는 'multinomial'을 사용할 수 있다.  

12. **verbose:**  
출력의 상세 정도를 설정한다. 0이면 출력이 없고, 1 이상의 값으로 설정하면 더 많은 정보가 출력된다.  

13. **warm_start:**  
이전에 학습한 모델을 재사용할지를 결정한다. True로 설정하면 이전 모델의 가중치를 초기값으로 사용하여 학습을 계속할 수 있다.  

14. **n_jobs:**  
병렬 처리를 위한 작업 수를 설정한다. None으로 설정하면 기본값이 사용되며, -1로 설정하면 모든 CPU 코어를 사용한다.  

15. **l1_ratio:**  
L1과 L2 정규화의 비율을 설정한다. 'elasticnet'을 사용할 때만 의미가 있으며, 기본값은 None이다.

In [60]:
# 모델 학습(로지스틱 회귀 - 적절한 알고리즘을 선택해서 훈련 시킴)

# 모델 초기화 (로지스틱 회귀 알고리즘 선택
# max_iter: 로지스틱 회귀는 내부적으로 경사하강법 같은 반복적 최적화 알고리즘으로 최적의 계수(가중치)를 찾아감. 
#           max_iter는 "이 반복을 최대 몇 번까지 시도할지"를 정하는 값임.
#           기본값 100: "100번 반복했는데 아직 최적값을 못 찾았다"는 뜻
#           그래서 max_iter=10000처럼 크게 늘려서 "반복 횟수 부족으로 수렴 못 하는 상황"을 방지하는 것
#           숫자 자체(1000이냐 10000이냐)는 크게 중요하지 않을 수 있음 (어차피 수렴하면 그 전에 멈춤)
#           하지만 "값이 너무 작으면" 실제로 문제가 생김 (수렴 못 하고 경고 뜨거나 성능 나쁜 모델이 나옴)
model = LogisticRegression(max_iter=10000)

# 모델 학습 (훈련 데이터로 실제 학습 수행)
model.fit(X_train, y_train)

# print(dir(model))


# [해결방법] 윈도우에서 model.fit 인코딩 에러
# HTML 다이어그램 출력 기능을 끄고 텍스트로 표시
# import platform
# print(platform.system())
# if platform.system() == 'Windows':
#     sklearn.set_config(display='text')


,"max_iter max_iter: int, default=100Maximum number of iterations taken for the solvers to converge.",10000
,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 

In [61]:
# 예측 (클래스 예측 및 확률 예측)
# X_test에 들어있는 각 행(row, 즉 각 샘플/데이터포인트) 하나하나에 대해 "너는 클래스 0이야, 아니면 1이야"라고 판정한 결과를 순서대로 배열로 뽑아주는 것
y_pred = model.predict(X_test)

# 모델이 각 테스트 샘플에 대해 예측한 값만 보여줌
print(y_pred)

# 예측값과 실제 정답(y_test)을 하나하나 비교해서, 맞았으면 True, 틀렸으면 False로 바꾼 배열
print(y_pred==y_test)

# 위에서 나온 True/False 배열에 어떤 종류의 값들이 있는지만 확인 (만약 [True]만 나오면 100% 다 맞았다는 뜻)
print(pd.Series(y_pred==y_test).unique())

# 제일 실질적인 정보. True가 몇 개, False가 몇 개인지 개수를 세줌.
# 이게 사실상 accuracy를 직접 손으로 계산해보는 과정
print(pd.Series(y_pred==y_test).value_counts())

# predict_proba()는 그 판정을 내리기 전 단계의 확률값을 그대로 보여줌
y_prob = model.predict_proba(X_test)
print(y_prob)

[1 0 0 1 1 0 0 0 1 1 1 0 1 0 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0
 1 0 1 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 1 1 1 0 0 1 1 1 0 0 1 1 0 0 1 0
 1 1 1 1 1 1 0 1 1 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 1 0 0 1 0 0 1 1 1 0 1 1 0
 1 0 0]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True False  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True False  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True False  True  True  True  True False  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True False  True]
[ True False]
True     109
False      5
Name: count, dtype: int64
[[1.21

In [62]:
# 출력: 혼합행렬
# confusion_matrix()는 기본적으로 행 = 실제값(actual), 열 = 예측값(predicted) 순서로 배열을 만든다.
cm = confusion_matrix(y_test, y_pred)
print(cm)

#                  예측
#             악성 0    양성 1
# 실제 0    [   39(TN)    4(FP)]
# 실제 1    [    1(FN)   70(TP)]

# 39개: 실제 악성 → 악성으로 정확히 예측 (정상적으로 잡아낸 암)
# 4개: 실제 악성인데 → 양성(정상)으로 잘못 예측 = FP ⚠️
# 1개: 실제 양성인데 → 악성(암)으로 잘못 예측 = FN
# 70개: 실제 양성 → 양성으로 정확히 예측

[[39  4]
 [ 1 70]]


In [ ]:
# 평가지표 계산
# Accuracy — "전체 중에 몇 개 맞췄나"
acc = accuracy_score(y_test, y_pred)    # (정답, 예측)

# Precision — "1(Positive)이라고 예측한 것 중에 진짜 1은 몇 개"
# 즉 "모델이 Positive라고 우겼을 때, 그게 얼마나 믿을만한가"를 보는 지표
prec = precision_score(y_test, y_pred)

# Recall — "실제 1(Positive)인 것 중에 몇 개를 제대로 잡아냈나"
# 즉 "진짜 Positive인 걸 얼마나 놓치지 않고 잡아냈는가"를 보는 지표
rec = recall_score(y_test, y_pred)

# F1 - Precision과 Recall 두 개를 하나의 숫자로 합쳐서 보여주는 지표
# 산술평균(단순 평균)이 아닌 "조화평균" 사용
# **즉 조화평균의 특징은 "둘 중 하나라도 0에 가까우면, 전체 점수도 확 끌어내린다"**는 거
# accuracy의 함정을 피하려고 precision/recall/f1을 같이 본다
f1 = f1_score(y_test, y_pred)

print('평가 지표')
print(f'Accuracy: {acc}')
print(f'Precision: {prec}')
print(f'Recall: {rec}')
print(f'F1 Score: {f1}')


# => Precision과 Recall은 항상 같이 봐야 함 (트레이드오프 관계)

평가 지표
Accuracy: 0.956140350877193
Precision: 0.9459459459459459
Recall: 0.9859154929577465
F1 Score: 0.9655172413793104


In [ ]:
target_names = data.target_names  # ['malignant', 'benign']
print(target_names)

'''
| 용어            | 한글 해석   | 설명                                                                          |
| -------------   | ------- | --------------------------------------------------------------------------- |
| **malignant**   | 악성 (암)  | 빠르게 자라고 전이할 가능성이 높은 종양이나 질병. 보통 **암(Cancer)** 을 뜻함. 치료가 어렵고 생명에 위협이 될 수 있음. |
| **benign**      | 양성  (비암성) | 성장하긴 하지만 전이하지 않으며 비교적 **위험하지 않은 상태**. 수술 등으로 완치 가능한 경우가 많음.                 |

- malignant: 악성 종양 (암) → 0 또는 Negative Class
- benign: 양성 종양 (비암성) → 1 또는 Positive Class
'''


# classification_report: accuracy_score(), precision_score(), recall_score(), f1_score() 이걸 한 줄로 다 뽑아주는 실무용 요약 함수

# 0. 전체 classification_report
print("Classification Report")
# target_names옵션을 설정하지 않으면 0과 1로 표시된다.
print(classification_report(y_test, y_pred))
print("Classification Report")
print(classification_report(y_test, y_pred, target_names=target_names))

['malignant' 'benign']
Classification Report
              precision    recall  f1-score   support

           0       0.97      0.91      0.94        43
           1       0.95      0.99      0.97        71

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114

Classification Report
              precision    recall  f1-score   support

   malignant       0.97      0.91      0.94        43
      benign       0.95      0.99      0.97        71

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114



In [69]:
# average: Literal['micro', 'macro', 'samples', 'weighted', 'binary'] | None

# 1. average=None (클래스별 개별)
print('average=None (클래스별 출력)')
print('Precision:', precision_score(y_test, y_pred, average=None))
print('Recall.  :', recall_score(y_test, y_pred, average=None))
print('F1 Score :', f1_score(y_test, y_pred, average=None))
print()

# 2. average='micro'
print("average='micro'")
print("Precision:", precision_score(y_test, y_pred, average='micro'))
print("Recall   :", recall_score(y_test, y_pred, average='micro'))
print("F1 Score :", f1_score(y_test, y_pred, average='micro'))
print()

# 3. average='macro'
print("average='macro'")
print("Precision:", precision_score(y_test, y_pred, average='macro'))
print("Recall   :", recall_score(y_test, y_pred, average='macro'))
print("F1 Score :", f1_score(y_test, y_pred, average='macro'))
print()

# 4. average='weighted'
print("average='weighted'")
print("Precision:", precision_score(y_test, y_pred, average='weighted'))
print("Recall   :", recall_score(y_test, y_pred, average='weighted'))
print("F1 Score :", f1_score(y_test, y_pred, average='weighted'))
print()

average=None (클래스별 출력)
Precision: [0.975      0.94594595]
Recall.  : [0.90697674 0.98591549]
F1 Score : [0.93975904 0.96551724]

average='micro'
Precision: 0.956140350877193
Recall   : 0.956140350877193
F1 Score : 0.956140350877193

average='macro'
Precision: 0.960472972972973
Recall   : 0.9464461185718964
F1 Score : 0.9526381387619444

average='weighted'
Precision: 0.9569049312470365
Recall   : 0.956140350877193
F1 Score : 0.9558014271241044



## avarage
### 0. average='binary' (default)
   - positive label을 1로 간주하고 계산한다.
   - y_true에 0과 1 두 개 클래스만 있어야 한다.

### 1. average=None (클래스별 성능 개별 출력)

| 클래스               | Precision | Recall | F1-score | Support |
| ----------------- | --------- | ------ | -------- | ------- |
| **0 (malignant)** | 0.97      | 0.91   | 0.94     | 43      |
| **1 (benign)**    | 0.95      | 0.99   | 0.97     | 71      |

- 각 클래스별로 정밀도, 재현율, F1-score를 개별적으로 계산하여 보여준다.
- 모델이 클래스 0 (악성 종양)을 상대적으로 덜 잘 맞추고 있다는 것을 파악할 수 있다.

### 2. average='micro' (전체 기준 - 샘플 단위의 합)  
- micro 평균은 모든 TP, FP, FN을 전 클래스 기준으로 합산한 뒤 계산한다.
- 이 경우 정확도(Accuracy) = Precision = Recall = F1-score가 된다.
- 총 정답 수: TP(전체 맞춤 수) = 0 클래스에서 39개 + 1 클래스에서 70개 = 109
- 전체 샘플 수: 114
- 따라서:    Accuracy = Precision = Recall = F1 = 109 / 114 ≈ 0.9561  

### 3. average='macro' (단순 평균)  
- 클래스별 점수를 동일한 비중으로 평균함
  Macro Precision = (0.97 + 0.95) / 2 = 0.96  
  Macro Recall    = (0.91 + 0.99) / 2 = 0.95  
  Macro F1-score  = (0.94 + 0.97) / 2 = 0.955 ≈ 0.95  

- 클래스 0과 1의 비중이 같다고 가정하고 평균 내기 때문에, 클래스 불균형이 있는 경우에는 왜곡이 있을 수 있다.

### 4. average='weighted' (샘플 수 기반 가중 평균)  
-  각 클래스의 점수에 해당 클래스의 샘플 개수(Support)를 곱해서 평균
  Weighted Precision = (0.97×43 + 0.95×71) / 114 ≈ 0.958    
  Weighted Recall    = (0.91×43 + 0.99×71) / 114 ≈ 0.961  
  Weighted F1-score  = (0.94×43 + 0.97×71) / 114 ≈ 0.961  

- 실제 출력값은 모두 반올림되어 0.96으로 나옴

- 데이터 불균형을 고려한 평균이므로, 실전에서 가장 신뢰도 있는 지표 중 하나임

### 5. average 옵션 요약

| 평균 방식      | 설명                    | 특징               | 언제 사용하면 좋은가?                 |
| ---------- | --------------------- |------------ | ---------------------------- |
| `None`     | 클래스별 개별 지표 확인         |  `array` 형태       | 특정 클래스 성능 비교 시               |
| `micro`    | 전체 샘플 기준으로 정밀도/재현율 계산 | 불균형 데이터에 취약      | 다중 클래스, 불균형 무시하고 전체 성능 확인 시  |
| `macro`    | 클래스별 단순 평균            | 클래스 중요도 균일할 때 사용 |클래스 간 균형 평가 시                |
| `weighted` | 클래스별 가중 평균            | 불균형 데이터에 적합      |**불균형 데이터에서의 전체 성능 평가** 시 유리 |


# 데이터가 불균형일 때 발생되는 문제   

불균형한 이진 분류로 만들기 위해 숫자 '7'만 True 나머지 숫자는 False로 설정

- 마찬가지로 fit은 아무것도 하지 않음
- predict에서는 무조건 0을 반환함
- 모든 예측을 다 0으로 하는 것! (모두 7이 아닌 다른 숫자라고 예측)
- 당연히 모델로서 말이 안 되는데 이것의 정확도를 측정

In [ ]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.base import BaseEstimator
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pd

In [ ]:
# MyFakeClassifier 알고리즘 정의

# BaseEstimator 상속 - fit(), predict() 같은 sklearn 표준 인터페이스를 따르는 "커스텀 모델"을 직접 만들 수 있음
class MyFakeClassifier(BaseEstimator):
    # 훈련할 메소드
    def fit(self,X,y):
        pass

    # 입력값으로 들어오는 X 데이터 셋의 크기만큼 모두 0값으로 만들어서 반환
    # 예측 데이터
    def predict(self,X):
        return np.zeros( (len(X), 1) , dtype=bool)

# 사이킷런의 내장 데이터 셋인 load_digits()를 이용하여 MNIST 데이터 로딩
digits = load_digits()

print(digits.data)
print(f'### digits.data.shape: {digits.data.shape}')
print(digits.target)
print(f'### digits.target.shape: {digits.target.shape}')

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
### digits.data.shape: (1797, 64)
[0 1 2 ... 8 9 8]
### digits.target.shape: (1797,)


In [ ]:
print(digits.target)

# 숫자가 7인 경우 True이고, 나머지는 False이므로
# 이를 1과 0으로 변환하기 위해서 astype(int)로 한 것이다.
y = (digits.target==7).astype(int)

print(len(y))
# 1797

print(pd.Series(y).value_counts())
# 0    1618
# 1     179

X_train, X_test, y_train, y_test = train_test_split(digits.data, y, random_state=42)
# 0    1618
# 1     179

print(pd.Series(y_train).value_counts())
# 0    1209
# 1     138

print(pd.Series(y_test).value_counts())
# 0    409
# 1     41

[0 1 2 ... 8 9 8]
1797
0    1618
1     179
Name: count, dtype: int64
0    1209
1     138
Name: count, dtype: int64
0    409
1     41
Name: count, dtype: int64


In [54]:
fakeclf = MyFakeClassifier()
fakeclf.fit(X_train, y_train)

fakepred = fakeclf.predict(X_test)
print('모든 예측을 0으로 하여도 정확도는: {:.3f}'.format(accuracy_score(y_test, fakepred)))

cf = confusion_matrix(y_test, fakepred)
print(f'Accuracy: {cf}')

f1 = f1_score(y_test, fakepred)
print(f'F1_score: {f1}')

recall = recall_score(y_test, fakepred)
print(f'recall_score: {recall}')

모든 예측을 0으로 하여도 정확도는: 0.909
Accuracy: [[409   0]
 [ 41   0]]
F1_score: 0.0
recall_score: 0.0


- 모든 예측을 0으로 했지만, 0 (7이 아닌 숫자)이 1 (숫자 7)보다 훨씬 많은 불균형 데이터였기 때문에, 정확도가 무려 90%가 나왔다.

- 이렇게 두 가지 예제로 불균형 데이터에서 정확도의 성능 평가지표로서 한계를 보였다