# numpy

In [ ]:
# numpy 설치하기
#!uv add numpy

In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.5.1


In [5]:
#!pip list | grep numpy
# windows에는 기본적으로 grep대시 findstr이 탑재되어 있음
#!uv pip list | findstr numpy

# macOS는 Unix 기반(BSD 계열)이라 grep이 터미널에 기본으로 깔려 있음
!uv pip list | grep numpy

442.57s - pydevd: Sending message related to process being replaced timed-out after 5 seconds


numpy                   2.5.1


In [6]:
# python을 이용한 계산
%time sum(range(1000000))

CPU times: user 15 ms, sys: 343 μs, total: 15.3 ms
Wall time: 15.8 ms


499999500000

In [ ]:
# numpy을 이용한 계산
%time np.sum(np.arange(1000000))

CPU times: user 1.36 ms, sys: 2.62 ms, total: 3.98 ms
Wall time: 2.87 ms


np.int64(499999500000)

In [11]:
# 2행 3열의 수치형 2차원 배열 정의
arr = np.array([[1, 2, 3],
               [4, 5, 6]])

print("배열의 차원:", arr.ndim, np.ndim(arr))   # 출력: 2
print("배열의 형태:", arr.shape, np.shape(arr))  # 출력: (2, 3)
print("원소 총 개수:", arr.size, np.size(arr))  # 출력: 6
print("데이터 타입:", arr.dtype)  # 출력: int64

# 정수형 데이터를 실수형(Float) 데이터 타입으로 강제 변환
float_arr = arr.astype(np.float64)
print("변경된 타입:", float_arr.dtype)  # 출력: float64



배열의 차원: 2 2
배열의 형태: (2, 3) (2, 3)
원소 총 개수: 6 6
데이터 타입: int64
변경된 타입: float64


In [13]:

a = np.array([1, 2, 3])
print(type(a))            # <class 'numpy.ndarray'>
print(a.dtype)            # int64 : 정수 64bit => 8byte

<class 'numpy.ndarray'>
int64


In [14]:
int64_a = np.array([1, 2, 3])
print(int64_a.dtype )
float32_b = int64_a.astype(np.float32)
print(float32_b )                 # array([1., 2., 3.]) -> . 이 나오면 실수라는 뜻
print(float32_b .dtype)           # dtype('float32')

int64
[1. 2. 3.]
float32


In [ ]:
# 1차원 배열 = 벡터
a = np.array([1,2,3])
print(a)           # [1 2 3]
print(dir(a))
print(type(a))     # <class 'numpy.ndarray'>
print(a.shape)     # (3,)

[1 2 3]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '_

In [16]:
# 2차원 배열 = 행렬
b = np.array([[1,2],[3,4]]) # 2행 2열
print(b)                # [[1 2][3 4]]
print(dir(b))
print(type(b))           # <class 'numpy.ndarray'>
print(b.shape)           # (2, 2)

[[1 2]
 [3 4]]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd

In [18]:
# 3차원 배열 = 텐서(tensor)
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) # 2층(공간, 면), 2행 , 2열
print(c)          # [[[1,2][3,4]]  
                  #  [[5,6][7,8]]]
print(dir(c))
print(type(c))     # <class 'numpy.ndarray'>
print(c.shape)     # (2, 2, 2)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__

In [21]:
# 문자 데이터가 하나라도 있으면 전체가 문자로 바뀐다.
# numpy는 homogeneous 즉 같은 데이터 타입만 저장 할 수 있다.
a = np.array([1, '2', 3])
print(a)             # ['1' '2' '3']

b = np.array(['a', 1, True])
print(b)              # array(['a', '1', 'True'], dtype='<U21')

c = np.array([True, False, True])
print(c)               # array([ True, False,  True])

d = np.array([True, False, True, 0, 1]) # False -> 0, True -> 1
print(d)                 #  array([1, 0, 1, 0, 1])

['1' '2' '3']
['a' '1' 'True']
[ True False  True]
[1 0 1 0 1]


In [22]:
a = np.zeros(3)
print(a)

[0. 0. 0.]


In [26]:
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [27]:
a = np.ones(3)
print(a)

[1. 1. 1.]


In [28]:
a = np.ones((2, 3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [29]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
a = np.eye(3, 2)
print(a)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [42]:
a = np.eye(3, 4, k=1)
print(a)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [46]:
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
a = np.full((2, 2), 1)
print(a)

[[1 1]
 [1 1]]


In [35]:
a = np.full((2, 2), [1, 2])
print(a)

[[1 2]
 [1 2]]


In [36]:
a = np.full((2, 2), [[1],[2]])
print(a)

[[1 1]
 [2 2]]


In [38]:
a = np.full((2, 2), [[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [47]:
a = np.empty(3)
print(a)

[1. 1. 1.]


In [48]:
a = np.empty((2,3))
print(a)

[[1. 0. 0.]
 [1. 0. 0.]]


In [51]:
a = np.linspace(0, 49)
print(a)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]


In [52]:
a = np.linspace(0, 5)
print(a)

[0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  3.87755102 3.97959184 4.08163265 4.18367347
 4.28571429 4.3877551  4.48979592 4.59183673 4.69387755 4.79591837
 4.89795918 5.        ]


In [ ]:
# endpoint=False로 설정하면 5가 포함 안됨
a = np.linspace(0, 5, endpoint=False)
print(a)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9]


In [ ]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [55]:
arr = np.arange(3, 10)
print(arr)

[3 4 5 6 7 8 9]


In [56]:
arr = np.arange(1, 10, 2)
print(arr)

[1 3 5 7 9]


In [57]:
arr = np.arange(0, 1, 0.1)
print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [59]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

b = np.ones_like(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 1 1]
 [1 1 1]]


In [61]:
a = np.array([[1., 2., 3.], [4., 5., 6.]])
print(a)

b = np.zeros_like(a)
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [63]:
a = np.array([[1., 2., 3.], [4., 5., 6.]])
print(a)

b = np.empty_like(a)
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [65]:
a = np.array([[1., 2., 3.], [4., 5., 6.]])
print(a)

b = np.zeros_like(a)
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [69]:
sum?

help(sum)


Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers

    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



Signature: sum(iterable, /, start=0)
Docstring:
Return the sum of a 'start' value (default: 0) plus an iterable of numbers

When the iterable is empty, return the start value.
This function is intended specifically for use with numeric values and may
reject non-numeric types.
Type:      builtin_function_or_method

In [71]:
np.array?

help(np.array)

Help on built-in function array in module numpy:

array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, ndmax=0, like=None)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          ndmax=0, like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or i

Signature:
np.array(
    object,
    dtype=None,
    *,
    copy=True,
    order='K',
    subok=False,
    ndmin=0,
    ndmax=0,
    like=None,
)
Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      ndmax=0, like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    require

In [73]:
a = [1, 2, 3]        # list
b = a
print(b)
print(a is b)        # 메모리 주소 비교 True
b[0] = 7
print(a)               # [7, 2, 3]           
print(b)                # [7, 2, 3]

[1, 2, 3]
True
[7, 2, 3]
[7, 2, 3]


In [74]:
a = [1,2,3]
b = a.copy()
id(a)                 # 133162358434304
id(b)                 # 133162358425280
print(a is b)         # 주소 비교 False
print(a == b)         # 값 비교 True

b[0] = 8
# a는 안바뀐다.
print(a)               # [1, 2, 3]
print(b)               # [8, 2, 3]
print(a is b)          # 메모리 주소 비교  False
print(a == b)          # 값 비교           False

False
True
[1, 2, 3]
[8, 2, 3]
False
False


In [ ]:
a = [[1,2,3]]
print(type(a))           # list

b = a.copy()
print(id(a))              # 4369408320
print(id(b))              # 4459967296

print(a is b)             # False
print(a == b)             # True

b[0][0] = 10
print(a[0])               # [10, 2, 3]
print(b[0])               # [10, 2, 3]

<class 'list'>
4369408320
4459967296
False
True
[10, 2, 3]
[10, 2, 3]


In [76]:
import copy

a = [[1,2,3]]
# list가 2차원일때 deep copy을 하기 위해서 copy모듈에 있는 
# deepcopy메소드를 사용한다.
b = copy.deepcopy(a) 

print(a[0] is b[0])        # 메모리 주소 False
print(a[0] == b[0])        # 값 True

b[0][0] = 10

print(a[0] is b[0])         # 메모리 주소 False
print(a[0] == b[0])         # 값 False

print(a)                    # [[1, 2, 3]]
print(b)                    # [[10, 2, 3]]

False
True
False
False
[[1, 2, 3]]
[[10, 2, 3]]


In [77]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr[arr > 5])

[6 7 8 9]


In [83]:
arr = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11]
])

# 행이 3개니까 라벨도 3개로 맞춰줌
axis_ABC = np.array(['A', 'A', 'B'])

bool_mask = axis_ABC == 'A'          # [True, True, False]
print(bool_mask)

result = arr[bool_mask]              # mask가 True인 행만 선택
print(result)
# [[0 1 2 3]
#  [4 5 6 7]]

[ True  True False]
[[0 1 2 3]
 [4 5 6 7]]


In [ ]:
a = np.arange(24).reshape(2,3,4) # 3차원(2층(면, 공간), 3행, 4열)
print(a)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [85]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [86]:
a[[0]]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [84]:
a[0]=a[0, :, :]=a[0,...]
print(a[0])  # indexing 기법
print(a[0, :, :]) # slicing 기법
print(a[0,...])  # ellipsis 기법(생략기법)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [88]:
print(a)
a[[0], :, :]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [89]:
print(a)
a[0, :, 1] 

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


array([1, 5, 9])

In [91]:
a[[0],:, [1]]

array([[1, 5, 9]])

In [93]:
a[[0], :, [1,3]]

array([[ 1,  5,  9],
       [ 3,  7, 11]])

In [94]:
a[:, 1, :]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [99]:
b = a[:, [1], :]
b.shape

(2, 1, 4)

In [103]:
a[[1]]

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [102]:
print(a)
a[[1], :, :]
b = a[[1], :, :]

b.shape

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


(1, 3, 4)

In [104]:
a[:, :, [1]]

array([[[ 1],
        [ 5],
        [ 9]],

       [[13],
        [17],
        [21]]])

In [97]:
a[:, :, 3]

array([[ 3,  7, 11],
       [15, 19, 23]])

In [105]:
a[:, :, [3]]

array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])

In [107]:
print(a)
a[:,:, -1]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


array([[ 3,  7, 11],
       [15, 19, 23]])

In [109]:
arr = np.array([[1, 2], [3, 4]])

dap = arr.flatten()
print(dap)                      # 출력 : [1 2 3 4]


# 메모리 공유 확인:: False
print(f'메모리 공유 확인:: {np.shares_memory(arr, dap)}')   
print(f'{arr is dap}')

[1 2 3 4]
메모리 공유 확인:: False
False


In [ ]:
# 1차원 12개 원소 배열을 3행 4열 2차원 배열로 변경
arr_1d = np.arange(12)
arr_2d = arr_1d.reshape(3, 4)

print(arr_1d)
print(arr_2d)


print(f'메모리 공유 확인:: {np.shares_memory(arr_1d ,arr_2d)}') # 메모리 공유 확인:: True
print(arr_1d is arr_2d) # is비교 : False

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
메모리 공유 확인:: True
False
